steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/forecasting-service:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/forecasting-service:latest'
      - '.'
    dir: 'forecasting-service'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/forecasting-service:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/forecasting-service:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'forecasting-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/forecasting-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/forecasting-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/forecasting-service:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
